### ISSUE TITLE
Getting a  TypeError: Cannot read property 'android' of undefined

### ISSUE THREAD

**Issue by getmetorajesh** [naderio/nativescript-google-maps-utils#1]
Great work @naderio, was working on something similar and came across your plugin. When trying to run it on android simulator it throws the below error, tried 
```
rm -rf node_modules platforms
tns install
```
but no luck.

full error log
```Javascript
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Error calling module function 

TypeError: Cannot read property 'android' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'/data/data/org.nativescript.testmaps/files/app/tns_modules/nativescript-google-maps-utils/index.js', line: 7, column: 34
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.testmaps/files/app/app.component.js', line: 5, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.testmaps/files/app/main.js', line: 4, column: 23
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
	at android.app.ActivityThread.-wrap1(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
	at andro
```

**Comment by naderio** [comment]
it appears that https://github.com/googlemaps/android-maps-utils is not installed. please do the following
```
tns plugin add nativescript-google-maps-sdk
tns plugin add nativescript-google-maps-utils
```
and let me know

**Comment by getmetorajesh** [comment]
thanks @naderio. that works.
